SELECT 
        order_line_id
        ,order_id
        ,stock_item_id
        ,description
        ,package_type_id
        ,quantity
        ,unit_price
        ,tax_rate
        ,picked_quantity
        ,picking_completed_when
        ,last_edited_by
        ,last_edited_when
        ,customer_id
        ,salesperson_person_id
        ,picked_by_person_id
        ,contact_person_id
        ,backorder_order_id
        ,order_date
        ,expected_delivery_date
        ,customer_purchase_order_number
        ,is_undersupply_backordered
        ,comments
        ,delivery_instructions
        ,internal_comments
        ,picking_completed_when
        ,last_edited_by
        ,last_edited_when

FROM 

